include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_const_declarations: info
    prefer_const_literals_to_create_immutables: info

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true